### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [SophiaVandewater/TeaCozy#5]
Grade: **Meets Expectations**

Overall this project is mostly working. It doesn't quite meet the specification as the elements are off center, but we can get much closer by adding the recommended CSS. I really liked that you used semantic elements for this project as it really helps with clarity for humans and search engines alike. Additionally, I would recommend adding alt attributes to your images to improve accessibility and help our users further in the event the image cannot be accessed. Next steps, I would look into learning about media queries in an effort to make your pages responsive so they will be viewable on all types of media such as phone, PC, laptop, etc: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

Good work.

**Comment by SophiaVandewater** [comment]
Thank you so much! Very helpful info.
